### ISSUE TITLE
Other states affected title on food recalls

### ISSUE THREAD

**Issue by kelle2dm** [BridgePhase/ctf#47]
The "Other states affected" title that appears over the map is off set. I would suggest moving the title  down and directly over the map in a "center" position.

**Comment by jgarciarbridgephase** [comment]
Ok I'll go ahead and center it. I can't move it down because it won't align properly with the grid. How's this? 
![screen shot 2015-06-24 at 3 04 12 pm](https://cloud.githubusercontent.com/assets/12414982/8339041/b3ef886e-1a82-11e5-998b-ca9c967df9a4.png)

**Comment by kelle2dm** [comment]
I like the location of this much more. Would it be possible to change the font color for the title to make it stand out?

**Comment by jgarciarbridgephase** [comment]
Hi @kelle2dm, this is now fixed. 

I implemented a "Test" environment so that we can test issues before we move to production. So can you please test this on http://54.175.58.210:8080/ctf/

Thanks!

**Comment by kelle2dm** [comment]
When testing in the "test" env. I am still seeing the "Other states affected" text appearing in black font. Is it possible to change this color to make the heading stand out? I do see the name of the food recall in blue which looks awesome! (Perhaps we could make them the same color?)

**Comment by jgarciarbridgephase** [comment]
So the "Other States" header stayed black because it uses the same layout and styling as the headers for "Reason for recall", etc.

**Comment by kelle2dm** [comment]
Ok thanks for clarifying!
